
CREATE DATABASE moneyz;

CREATE TABLE tblUser(
    Id int NOT NULL AUTO_INCREMENT,
    Username VARCHAR(255) UNIQUE,
    Password VARCHAR(255),
    Created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    Updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (Id)
);
CREATE TABLE tblMoneyz(
    Id INT NOT NULL AUTO_INCREMENT,
    User_id INT,
    Moneyz INT,
    PRIMARY KEY (Id),
    FOREIGN KEY (User_id) REFERENCES tblUser(Id)
);

